language: go
go:
  - 1.13
script:
  - go build main.go
notifications:
  email:
    recipients:
      - 362761534@qq.com
    on_success: change
    on_failure: always
git:
    submodules: false
env:
  - GO111MODULE=on